services:
  app:
    container_name: oymeals
    image: cosmtrek/air
    working_dir: /app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./views:/app/views
      - ./handlers:/app/handlers
      - ./static:/app/static
      - ./main.go:/app/main.go
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
